### ISSUE TITLE
Question about Getting The Company Details From SearchOfficerAsync

### ISSUE THREAD

**Issue by JulianGuppy** [kevbite/CompaniesHouse.NET#100]
I am using the API call SearchOfficerAsync to search for a person (I am then going through the results and using the date of birth I already have in my database to select the right individual Officer)

I get a Link (offier.Links.Self) which if followed takes me to the directorships for that person. Does your API expose the ability for me to in effect say Get me the companies for this person.... 

Is this possible?

**Comment by JulianGuppy** [comment]
I just say this on the pull request "added ability to get all appointments for an officer"..... I really want this feature. please let me know when this is ready/available.

**Comment by kevbite** [comment]
I think what you want is in the latest version, if you check out this integration test it might be exactly what you require [OfficersTestsValid](https://github.com/kevbite/CompaniesHouse.NET/blob/354a5a648bf71ae21fbd10c7c2dace49ce9447af/src/CompaniesHouse.IntegrationTests/Tests/AppointmentsTests/OfficersTestsValid.cs)

Does that work for your scenario?

**Comment by JulianGuppy** [comment]
I think I asked for the feature that has just been done, when will that be in the nuget? Id rather use the nuget than have to pull the code and build it... :) is that possible

**Comment by kevbite** [comment]
It will be in the latest package, master auto builds and publishes to nuget. It's just we don't seem to have that functionality in the read me yet.

**Comment by JulianGuppy** [comment]
I am on 6.1.5, and I dont have that method in my companieshouseClient.... something screwy with nuget perhaps?

**Comment by kevbite** [comment]
OK, I'll take a look today and see what's what. Not sure what's wrong.

**Comment by kevbite** [comment]
Right, I see what it is... your scenario is a little different from the one in the PR. I've altered the code and pushed a new package that will allow you to get an Officer Id from a search.

I've also added a test scenario with an example here - https://github.com/kevbite/CompaniesHouse.NET/blob/master/src/CompaniesHouse.ScenarioTests/SearchForAnOfficerAndFetchCorrespondingCompanyScenarioTests.cs#L22

Try that and see if that works for your case too. 😄

**Comment by JulianGuppy** [comment]
ok I updated to 6.1.6 However,  I do not have the method GetAppointmentsAsync in my client, something is still wrong? my visual studio will not see that method  - i cant work out why not, I can open the DLL with ildasm and I can see the method, I check my packages.config and its pointing at 6.1.6, howevr in visual studio it refuses to believe that there is such a method
![cantseemethod](https://user-images.githubusercontent.com/1077855/51083330-63099a00-1710-11e9-8e08-6614fab18318.png)
![butitsthere](https://user-images.githubusercontent.com/1077855/51083331-6866e480-1710-11e9-9595-3f0243858d46.png)

**Comment by JulianGuppy** [comment]
Is it missing from the Interface ICompaniesHouseClient? I wonder

**Comment by kevbite** [comment]
@JulianGuppy you're totally correct.

Just looked and it's not exposed on the `ICompaniesHouseClient` facade, total oversight on that one, sorry about that. In theory, all our tests should use the interface as that's what we expect people will be using.

I've updated the code in #102 which will enable this now and will be released in 6.1.7.

**Comment by JulianGuppy** [comment]
Thank you, You have helped me out as I needed to make this work asap,,, I was about to go off and do all the low level stuff (which I wanted to avoid) Much Appreciated

**Comment by kevbite** [comment]
Well if you need any other help just create another issue 👍
