### ISSUE TITLE
Date of Dissolution has changed to Date of Cessation

### ISSUE THREAD

**Issue by adancy** [kevbite/CompaniesHouse.NET#105]
In CompanyProfile.cs lines 46-48 the "date_of_dissolution" property should actually be "date_of_cessation" . 

According to http://forum.aws.chdev.org/t/company-profile-date-of-cessation-query/541 this was a mistake in the original documentation (which presumably you based your code on) - this has now been corrected in the docs at https://developer.companieshouse.gov.uk/api/docs/company/company_number/companyProfile-resource.html

**Comment by kevbite** [comment]
Hey @adancy, thanks for bringing that to our attention.

Should be a pretty easy fix so we'll add it to the backlog!

**Comment by adancy** [comment]
No problem. I'll see if I can knock up a pull request when I get a moment. I just want to see if I come across any other differing fields first.

Great project - it's saving me a lot of time not having to write it all myself!

**Comment by kevbite** [comment]
@adancy much appreciated, yeah the API has changed a lot since the first beta release of it which this was targeting, however, it works 99% of the time and grateful that people are raising issues where things have changed.

Glad you've found the library useful too.

**Comment by kevbite** [comment]
All Merged in via PR #106 and is part of the [7.0.0](https://www.nuget.org/packages/CompaniesHouse/7.0.0) Release

Thanks for helping out!
