### ISSUE TITLE
New Filing Sub-Category document-replacement

### ISSUE THREAD

**Issue by invdev-rh** [kevbite/CompaniesHouse.NET#107]
Hi,

I am getting the following error:
`Newtonsoft.Json.JsonSerializationException: Error converting value "document-replacement" to type 'CompaniesHouse.Response.FilingSubcategory'. Path 'items[1].subcategory', line 1, position 838. ---> System.ArgumentException: Requested value 'document-replacement' was not found.`

Looking at the attributes in FilingSubcategory it seems document-replacement is not listed. Can you please look into it for me.

Thanks,
Rob.

**Comment by kevbite** [comment]
Hey @invdev-rh,

You got a company number which is occoring for so I can reproduce it?

I'll try to get a fix in for this by tonight.

Cheers,

Kev

**Comment by invdev-rh** [comment]
Yes, here it is: 09018331 

Thanks for that Kev!

**Comment by kevbite** [comment]
@invdev-rh this has now been fixed and is part of the release [7.0.1](https://www.nuget.org/packages/CompaniesHouse/7.0.1) feel free to grab the latest from [NuGet](https://www.nuget.org/packages/CompaniesHouse/7.0.1).

Thanks for raising this issue.

**Comment by invdev-rh** [comment]
Fast work, thank you very much!
