### ISSUE TITLE
"Authentication Failed because the remote party has closed the transport stream" Error

### ISSUE THREAD

**Issue by wreid306** [kevbite/CompaniesHouse.NET#110]
Hi Kev, 

Been using this for a few years now, have recently come across this error, tried updating to latest version with no joy. Any ideas?

its the SearchCompanyAsync method

![image](https://user-images.githubusercontent.com/10054139/58468684-ebc02a00-8135-11e9-85df-0f98d0c891bb.png)

**Comment by wreid306** [comment]
Turns out this is related to TLS, Companies house have removed support for TLSv1.0, so need to make sure application used 1.1 or 1.2

in my case, adding the following to 'application start' worked 
(.net framework 4.7.2)
(using System.Net;)

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by kevbite** [comment]
@wreid306 thanks for posting the reason and solution around this issue 👍

**Comment by AlwaysVbNet** [comment]
@wreid306 Nice one
