### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by shauncassingham** [kevbite/CompaniesHouse.NET#112]
Trying to use CompanySearch, but coming up with the following error when awaiting the result;

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (No connection could be made because the target machine actively refused it)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at CompaniesHouseRequester.Program.Main(String[] args) in 

.....\Program.cs:line 102

Inner Exception 1:
HttpRequestException: No connection could be made because the target machine actively refused it

Inner Exception 2:
SocketException: No connection could be made because the target machine actively refused it

**Comment by kevbite** [comment]
@shauncassingham thanks for the update!
