### ISSUE TITLE
resigned_on bombing out

### ISSUE THREAD

**Issue by obinna962** [kevbite/CompaniesHouse.NET#123]
Hi Guys.

I downloaded this code yesterday and I realised that there's something weird about the JSON structure when using 

[https://developer.companieshouse.gov.uk/api/docs/officers/officer_id/appointments/appointmentList-resource.html] *_client.GetAppointmentsAsync*. 

The property **resigned_on** on the JSON files sometimes appear and most times it does appear. Therefore when the serialiser maps the object, it fails. 

This issue is to do with how CompanyHouse coder implemented the system. I believe, there's a workaround but I could not figure out how to fix it. Any volunteers pls?

**Comment by kevbite** [comment]
I've added this property to the model and from a bit of testing, this seems to work fine. Can you check in the latest version that this is a problem? Thanks

**Comment by kevbite** [comment]
I'm closing this issue off as this should be working fine in the latest version [7.5.0](https://www.nuget.org/packages/CompaniesHouse/7.5.0)
