### ISSUE TITLE
Where can I get the raw JSON from the request within this library for reference.

### ISSUE THREAD

**Issue by mattu08** [kevbite/CompaniesHouse.NET#125]
Hi,

Where can I get the raw JSON from the request within this library for reference.

Is there an entry point so I can grab the raw JSON coming in from the API request just to have the request as backup.

Kind regards,

Matt

**Comment by kevbite** [comment]
The requests for the API are mostly GET requests with the parameters on a query string, these are built up in different places depending on which search/lookup you are executing.

Ideally, if you want to inspect the requests and responses from the library, we'd need to extend it so you can pass in a custom `DelegatingHandler`.

We could maybe accept a client handler in the settings and plumb it in at the [HttpClientFactory](https://github.com/kevbite/CompaniesHouse.NET/blob/master/src/CompaniesHouse/HttpClientFactory.cs#L16).

I'm quite surprised this is not already extendable in this way but I guess people are mocking out the `ICompaniesHouseClient`.

**Comment by mattu08** [comment]
Interesting, maybe something like the following that is addressed in [CompaniesHouse.Tests/StubHttpMessageHandler.cs](https://github.com/kevbite/CompaniesHouse.NET/blob/219c4242ddfeb462424351653d4b2717a1b4a253/src/CompaniesHouse.Tests/StubHttpMessageHandler.cs#L9) e.g. using `HttpClient` with the `HttpResponseMessage` to pull back the RAW JSON request. Example using: `message.Content.ReadAsStringAsync();`

**Comment by kevbite** [comment]
Yeah something like that, once we allow people to add in their own `HttpMessageHandler` to use as a handler then they'll be able to take over from that point.

I'll add something later tonight, and give you an example 👍.

**Comment by mattu08** [comment]
Cheers for looking into this @kevbite 👍 Sounds good!

**Comment by kevbite** [comment]
I've just updated the code in the latest version ([7.6.0](https://www.nuget.org/packages/CompaniesHouse/7.6.0)) so you can customize the `HttpMessageHandler` that is being used.

Here's some sample code to get it working, you'll need your own custom delegating handler:
```csharp
public class MyDelegatingHandler : DelegatingHandler
{
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        string requestBody;
        if (request.Content != null)
        {
            requestBody = await request.Content?.ReadAsStringAsync();
        }

        var result = await base.SendAsync(request, cancellationToken);
        var responseBody = await result.Content.ReadAsStringAsync();

        return result;
    }
}
```

Then within the creation of the `CompaniesHouseClient` you can pass in some settings like the following:

```csharp
 Func<HttpMessageHandler> httpMessageHandlerCreator =
    () => new MyDelegatingHandler()
    {
        InnerHandler = CompaniesHouseSettings.DefaultHttpMessageHandlerCreator()
};

var settings = new CompaniesHouseSettings(CompaniesHouseUris.Default, Keys.ApiKey, httpMessageHandlerCreator);

_client = new CompaniesHouseClient(settings);
```

**Comment by mattu08** [comment]
@kevbite Excellent work! I managed to get this working with the above examples, slightly modified by pulling in the `var responseBody = await result.Content.ReadAsStringAsync();` directly from the public `class MyDelegatingHandler : DelegatingHandler`, Class. Again thanks for your help! 👍

**Comment by kevbite** [comment]
No worries @mattu08, glad it sorted out your problem

**Comment by mattu08** [comment]
I'll close issue.  If you had a buymeacoffee i'd drop you a few quid, thanks for your help!

**Comment by sakisk** [comment]
> @sakisk I'll close issue. If you had a [buymeacoffee](https://www.buymeacoffee.com/) i'd drop you a few quid, thanks for your help!

thanks @mattu08 i'll set it up and first thing to do would be to buy a coffee for @kevbite that have been maintaining this code for all these years now 👏 🏅

**Comment by mattu08** [comment]
@sakisk @kevbite I see what I did here 🤦‍♂️😂 I @ Tagged the wrong person, But i agree great idea!

**Comment by kevbite** [comment]
No worries glad to be useful :-) 

I do have a Buy me a coffee account if really fancy buying me a coffee 😉 

buymeacoff.ee/d5qgmSF

**Comment by mattu08** [comment]
@kevbite No problem at all and thanks for your help! ☕ keep up the good work! 👍
