### ISSUE TITLE
Branch Companies (Company Profile)

### ISSUE THREAD

**Issue by johnmackerras** [kevbite/CompaniesHouse.NET#128]
Branch Companies dont seem to be suported. Please include the following fields in the Company Profile from these API fields.

branch_company_details 
branch_company_details.business_activity 
branch_company_details.parent_company_name   
branch_company_details.parent_company_number

Source: 
https://developer.companieshouse.gov.uk/api/docs/company/company_number/companyProfile-resource.html

**Comment by kevbite** [comment]
Branch Companies are now part of version [7.8.0](https://www.nuget.org/packages/CompaniesHouse/7.8.0)
