### ISSUE TITLE
New Enumrerations for Response

### ISSUE THREAD

**Issue by johnmackerras** [kevbite/CompaniesHouse.NET#129]
CompaniesHouse.Response needs some more/new enumerations:

CompaniesHouse.Response.FilingCategory
- other
- voluntary-arrangement

CompaniesHouse.Response.FilingSubcategory
- alter

CompaniesHouse.Response.PersonsWithSignificantControl.PersonWithSignificantControlKind
- super-secure-person-with-significant-control
- legal-person-person-with-significant-control

Note: Super Secure is just a person object wth identifiers removed

Note: Legal Person is a new Kind which had two unique fields 'LegalAuthority' and 'LegalForm'.

**Comment by johnmackerras** [comment]
Sorry,
voluntary-arrangement is in FilingSubcategory, not FilingCategory

**Comment by kevbite** [comment]
Hey @johnmackerras 
I can't seem to see them extra fields of `LegalAuthority` and `LegalForm` in the docs?
https://developer.companieshouse.gov.uk/api/docs/company/company_number/persons-with-significant-control/list-resource.html

**Comment by kevbite** [comment]
The new enumerations are now part of version [7.8.0](https://www.nuget.org/packages/CompaniesHouse/7.8.0)

**Comment by johnmackerras** [comment]
Hi Kevin,

https://developer.companieshouse.gov.uk/api/docs/company/company_number/persons-with-significant-control/legalPerson-resource.html

Look for
identification.legal_form
identification.legal_authority

**Comment by kevbite** [comment]
This library only currently does the listing of the company persons with significant control.
https://github.com/kevbite/CompaniesHouse.NET/blob/master/src/CompaniesHouse/CompaniesHousePersonsWithSignificantControlClient.cs#L20


There seem to be loads more endpoints now to get more details and it seems them properties are on the resources:
- get corporate entities
- get individual
- get legal persons
- get statement
- get super secure person

https://developer.companieshouse.gov.uk/api/docs/company/company_number/persons-with-significant-control/listPersonsWithSignificantControl.html

**Comment by sakisk** [comment]
Closing this as work scheduled in #144 will add all enumerations for each endpoint
