### ISSUE TITLE
Please support .Net Core 3.1 / .Net Standard 2.1

### ISSUE THREAD

**Issue by johnmackerras** [kevbite/CompaniesHouse.NET#130]
Please support Latest .Net Core products (.Net Core 3.1 / .Net Standard 2.1)

**Comment by kevbite** [comment]
Hello @johnmackerras, netstandard1.1 is netcore3.1 and netstandard2.1 compatible

**Comment by kevbite** [comment]
Please see *.NET implementation support* table
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by kevbite** [comment]
I've added netstandard 2.0 support as recommended in the MS Docs, this was in issue https://github.com/kevbite/CompaniesHouse.NET/issues/131

I'm going to close this issue unless there is a need to directly support these targets.
