### ISSUE TITLE
Missing Last Accounts Type

### ISSUE THREAD

**Issue by MattHemus** [kevbite/CompaniesHouse.NET#133]
Hi,

Could you add the following Last Accounts Type to the enum;

unaudited-abridged

An example company that returns this is PLAN PROCURE MANAGE LIMITED, 06450589.

The missing enum is currently causing an exception when requesting this company.

Many Thanks

Matt

**Comment by kevbite** [comment]
Hello @MattHemus ,

I've added the value to the enum and check that it works fine with "PLAN PROCURE MANAGE LIMITED, 06450589".

Thanks for raising this issue.

The fix will be in version [7.8.3](https://www.nuget.org/packages/CompaniesHouse/7.8.3), this can be downloaded from [NuGet](https://www.nuget.org/packages/CompaniesHouse/7.8.3).

**Comment by MattHemus** [comment]
Thanks for sorting the issue so quickly, installed latest package and everything is working okay.
