### ISSUE TITLE
Further enumerations (after release 7.8.4)

### ISSUE THREAD

**Issue by johnmackerras** [kevbite/CompaniesHouse.NET#135]
**Further enumerations (after release 7.8.4)**

Hi, I have uncovered some more missing enums. A lot of these seem to be newly added (as of two months ago) and you don't know about them until you hit them. I have tried to provide company numbers where I can so you have a reference for testing.

Thanks,

John

&nbsp;

**- CompaniesHouse\Response\FilingCategory.cs**

[EnumMember(Value = "reregistration")] ReRegistration,
Relevant Company numbers: 11852026, 09430736, SC564296, 11231735

[EnumMember(Value = "certificate")] Certificate,
Relevant Company numbers: FC023436, FC020067, FC027549, FC012542

&nbsp;

**- CompaniesHouse\Response\FilingSubcategory.cs**

[EnumMember(Value = "register")] Register,
Relevant Company numbers: 10655869, 10372233, 08944304, 10650233

[EnumMember(Value = "receiver")] Receiver,
Relevant Company numbers: 03944267, 04940944, 05669709, 04391172

[EnumMember(Value = "voluntary-arrangement-moratoria")] VoluntaryArrangementMoratoria,
Relevant Company numbers: 07749192, 06997265, 06637395, 04946135

[EnumMember(Value = "acquire")] Acquire,
Relevant Company numbers: 04315433, 08475208, 09102579, 10356888

[EnumMember(Value = "trustee")] Trustee,
Relevant Company numbers: 10473003

[EnumMember(Value = "mortgage")] Mortgage,
Relevant Company numbers: 02532302, 02216353

[EnumMember(Value = "transfer")] Transfer,
Relevant Company numbers: SE000122

&nbsp;

**- CompaniesHouse\Response\PersonsWithSignificantControl\PersonWithSignificantControlNatureOfControl.cs**

[EnumMember(Value = "part-right-to-share-surplus-assets-75-to-100-percent")] PartRightToShareSurplusAssets75To100Percent,
Maxim Semenov, Co Num: SL018060
Andrey Feklistov, Co Num: SL016462
Oracle Corporation, Co Num: SL003791

[EnumMember(Value = "part-right-to-share-surplus-assets-50-to-75-percent-as-trust")] PartRightToShareSurplusAssets50to75PercentAsTrust,
Lyndon Lea, Co Num: SL005219

[EnumMember(Value = "right-to-appoint-and-remove-person")] RightToAppointAndRemovePerson,        
Maxim Semenov, Co Num: SL018060
Lion Capital General Partners Llp, Co Num: SL005219
Andrey Feklistov, Co Num: SL016462

&nbsp;

**- CompaniesHouse\Response\FilingHistoryStatus.cs
Sorry, I don't save these in my data set but did get errors for these statuses** 

[EnumMember(Value = "filing-history-available-no-images-limited-partnership-from-1988")]
FilingHistoryAvailableNoImagesLimitedPartnershipFrom1988,

[EnumMember(Value = "filing-history-available-assurance-company-before-2004")]
FilingHistoryAvailableAssuranceCompanyBefore2004,

[EnumMember(Value = "filing-history-available-limited-partnership-from-2014")]
FilingHistoryAvailableLimitedPartnershipFrom2014,

[EnumMember(Value = "filing-history-not-available-industrial-and-provident-society")]
FilingHistoryNotAvailableIndustrialAndProvidentSociety,

[EnumMember(Value = "filing-history-not-available-limited-partnership-before-1988")]
FilingHistoryNotAvailableLimitedPartnershipBefore1988,

[EnumMember(Value = "filing-history-not-available-royal-charter")]
FilingHistoryNotAvailableRoyalCharter,

[EnumMember(Value = "filing-history-not-available-scottish-industrial-and-provident-society")]
FilingHistoryNotAvailableScottishIndustrialAndProvidentSociety,

[EnumMember(Value = "filing-history-not-available-northern-ireland-industrial-and-provident-society")]
FilingHistoryNotAvailableNorthernIrelandIndustrialAndProvidentSociety,

&nbsp;

**- CompaniesHouse\Response\ResolutionCategory.cs
Sorry, again no example.**

[EnumMember(Value = "insolvency")]
Insolvency,

**Comment by kevbite** [comment]
Hey @johnmackerras 

Thanks for raising the issue and thanks for all the detail, I'll try to sort out a new release as soon as possible so we can get these fixed for everyone.

Kev

**Comment by kevbite** [comment]
Sorry about the delay in sorting this out. This is all sorted in v[7.8.7](https://www.nuget.org/packages/CompaniesHouse/7.8.7). Any other problems feel free to just raise another issue. Thanks
