### ISSUE TITLE
Post data api

### ISSUE THREAD

**Issue by ahmed0304** [kevbite/CompaniesHouse.NET#140]
How to post data to companies house using api. 
Is that possible?
If yes then kindly guide

**Comment by DavidBetteridge** [comment]
@ahmed0304 I'm intrigued by your question!  Do you have a requirement to be able to create (or update) multiple companies?

**Comment by ahmed0304** [comment]
I want to send data using ConfirmationStatement. Xsd to companyhouse uain asp. Net
But don't know how

**Comment by kevbite** [comment]
Hey @ahmed0304, It doesn't look like the Companies House API supports submitting any data, it's only a read-only API.

**Comment by kevbite** [comment]
I'm going to close this ticket. If you require any more help please raise another issue.
