### ISSUE TITLE
Companies type missing error, new types need to be added

### ISSUE THREAD

**Issue by mattu08** [kevbite/CompaniesHouse.NET#149]
Hi,

I started to get a few errors for the following company types:

UKEIG example: GE000100
UK SOCIETAS example: SE000010

Then realized that the two types were missing, could you add the missing company types:

`ukeig`
`united-kingdom-societas`

To /src/CompaniesHouse/Response/CompanyType.cs
https://github.com/kevbite/CompaniesHouse.NET/blob/efef661d99dc64b38ed560e6d908695649f3ac1e/src/CompaniesHouse/Response/CompanyType.cs

Cheers,

Matt

**Comment by kevbite** [comment]
Hey @mattu08, thanks for raising this issue, I've updated the code to reflect the API responses. You're faster at finding the API changes than their own [api-enumeration](https://github.com/companieshouse/api-enumerations/blob/master/constants.yml#L46) documentation being updated 😉.

**Comment by kevbite** [comment]
This is now in the NuGet release [7.9.4](https://www.nuget.org/packages/CompaniesHouse/7.9.4). If you spot any other changes please feel free to open another issue. Thanks.

**Comment by mattu08** [comment]
Haha, No problem @kevbite will do! Thanks for adding the fix in 👍.
