### ISSUE TITLE
New Company CompanyStatusDetail Status need to be added.

### ISSUE THREAD

**Issue by mattu08** [kevbite/CompaniesHouse.NET#150]
Hi,

Just found two errors for missing Status:

`converted-to-ukeig` Example: GE000091
`converted-to-uk-societas` Example SE000010

These are missing from the following location: `CompaniesHouse.Response.CompanyStatusDetail`
https://github.com/kevbite/CompaniesHouse.NET/blob/master/src/CompaniesHouse/Response/CompanyStatusDetail.cs

Thanks again,

Matt

**Comment by mattu08** [comment]
Hopefully there are no more issues with these two linked to other types etc. Also having `converted-to-` is slightly worrying, just in case Companies House has started to use this structure for other company types etc. There would then be quite a few too add in.

**Comment by kevbite** [comment]
Just pushed up the 2 changes for them, I agree that would be slightly annoying but if they followed some convention we could convert it into something a little easier.

**Comment by kevbite** [comment]
This is in the latest NuGet package now [7.9.5](https://www.nuget.org/packages/CompaniesHouse/7.9.5)

**Comment by mattu08** [comment]
I agree it's pretty much like a break and fix type of scenario at the moment with them, anyway thanks again for getting this added in. Cheers 👍

**Comment by mattu08** [comment]
I'll close the ticket.
