### ISSUE TITLE
Charges type conversion exception 

### ISSUE THREAD

**Issue by mattu08** [kevbite/CompaniesHouse.NET#151]
Hi,

I have been testing the charges functionality recently and have started getting an exception when performing a basic charges search.

Exception:

`Newtonsoft.Json.JsonReaderException: 'Could not convert string to integer: 3011770624. Path 'items[1].insolvency_cases[0].transaction_id', line 1, position 2806.'`

Company Reg number tested on: `03487070`

CompaniesHouse.NET v7.9.5 most recent build.

It's a bit of an odd error, but looks to be a conversion issue probability due to a companies house change.

Cheers,

Matt

**Comment by kevbite** [comment]
Hey, thanks for raising, just checked their documentation and it still says it should be passing back an integer. So guess they've decided to start passing back a string of an integer...
![image](https://user-images.githubusercontent.com/5544715/115158283-50b3fe80-a085-11eb-8ed5-29fb77de02d8.png)
![image](https://user-images.githubusercontent.com/5544715/115158837-1a2bb300-a088-11eb-93a4-fd09fc8b5c98.png)

**Comment by kevbite** [comment]
Just realized the problem, the value is coming back which is over the maximum size for an int.

**Comment by mattu08** [comment]
Good find! 👍 I’ll let you know if I find anymore like this, thanks for looking into this.

**Comment by kevbite** [comment]
@mattu08 it's not pushed to NuGet yet as we're having a bit of a problem with the companies house api throttling our tests. I might just disable the tests for the older frameworks as these are not supported by MS anyway now.
