### ISSUE TITLE
Question: Is it possible to create a new LTD company using this wrapper/api?

### ISSUE THREAD

**Issue by sahgilbert** [kevbite/CompaniesHouse.NET#175]
1. Is it possible to create a new LTD company using the companies house REST api?
2. If so, does this C# wrapper support this functionality?

Thanks

**Comment by kevbite** [comment]
@sahgilbert sadly the API that this uses does not expose any endpoints to create new companies. This wraps up the [Companies House Public Data API](https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/reference).

I don't think there are any endpoints that companies house expose that provide that functionality

**Comment by sahgilbert** [comment]
Understood, thank you.
