### ISSUE TITLE
Include response headers in failed requests

### ISSUE THREAD

**Issue by bernhard-hofmann** [kevbite/CompaniesHouse.NET#181]
This is a feature request.

I'd like to propose a change that will include response header details in the `Data` property of the exception thrown for unsuccessful requests.

The calls to `response.EnsureSuccessStatusCode()` will throw without adding headers. In the case of a 503 or 429, the `Retry-After` header could be invaluable for correct behaviour on the part of the client. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

If you're in agreement, I'm offering to produce a PR that will either replace the call to the framework method (`EnsureSuccessStatusCode`) or catch it, add the necessary details, and then throw it (it does other things such as dispose the content so might be worth "piggybacking").

**Comment by BernhardHofmannAtDwellant** [comment]
Happy for you to close this issue now @kevbite. Thank you for the very swift merge and publish!
