### ISSUE TITLE
Add support for new Company Statuses and Types

### ISSUE THREAD

**Issue by BernhardHofmannAtDwellant** [kevbite/CompaniesHouse.NET#185]
[The Companies House (CH) company search specification](https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/companysearch?v=latest) lists a type and two statuses that are not currently supported. Specifically;

* Company statuses `registered` and `removed`
* Company type `registered-overseas-entity`

These need to be supported to avoid exceptions when parsing the CH response.

**Comment by kevbite** [comment]
This is release in NuGet version [7.11.7](https://www.nuget.org/packages/CompaniesHouse/7.11.7)
