### ISSUE TITLE
Error converting value "managing-officer" to type 'CompaniesHouse.Response.Officers.OfficerRole'. 

### ISSUE THREAD

**Issue by whitecobalt** [kevbite/CompaniesHouse.NET#197]
In the last 48 hours I have started receiving this error:

Error converting value "managing-officer" to type 'CompaniesHouse.Response.Officers.OfficerRole'. 
Path 'items[0].officer_role', line 1, position 741. (793ab109-e924-43e2-ae4c-37b07bd9297b)

It looks like CH has added a new type to that field and it is missing from the enum?

**Comment by kevbite** [comment]
@whitecobalt a fix has been released for this issue and is in version [7.12.4](https://www.nuget.org/packages/CompaniesHouse/7.12.4)
