### ISSUE TITLE
New FilingCategory enum values

### ISSUE THREAD

**Issue by shandybob76** [kevbite/CompaniesHouse.NET#209]
Hi,

I've been using your CompaniesHouse.NET implementation, and pulled in a load of company profiles, however there are a few which do not deserialize due to missing FilingCategory values;
- "officer"
- "social-landlord"

"officers" plural seems to exist, but some companies come back with "officer" singular.

I'll add these into a branch and PR it over for your consideration.

Cheers

Rob.

**Comment by shandybob76** [comment]
Note "social-landlord" is missing on FilingSubcategory too.

**Comment by shandybob76** [comment]
Example company numbers
- "OC361169"
- "06395296"
- "00908333"

**Comment by shandybob76** [comment]
Hi @kevbite - I just pushed the PR for your consideration, cheers

**Comment by shandybob76** [comment]
It's a shame Companies House don't have a definitive list! The docs are a little out of date that they have here

https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/filinghistoryitem?v=latest

**Comment by kevbite** [comment]
@shandybob76 we've always had that problem, we've hit enum values that haven't even been listed for 6+ months before. As originally we did think about pulling their list and building it always with the latest list but that's impossible as they don't declare them all.

**Comment by kevbite** [comment]
I've merged in the PR and is released in [8.0.29](https://www.nuget.org/packages/CompaniesHouse/8.0.29)

Thanks!
