### ISSUE TITLE
Adding other search types / endpoints

### ISSUE THREAD

**Issue by rcocks** [kevbite/CompaniesHouse.NET#29]
Hello, are there any plans to implement other search types?

The Companies House API supports the following search types as described here: https://developer.companieshouse.gov.uk/api/docs/search-overview/search-overview.html
 
There are

- [x] Search All
- [x] Search company information
- [x] Search for officer information
- [x] Search for disqualified officer information

Are there any plans to add support for the additional search types, in particular "search all" and "search officers" would be most useful.

I can look to implement this in my own fork if you aren't planning to add these. It will require adding a generic "Search" response type which can then be transformed into the other types.

Thanks

**Comment by kevbite** [comment]
Hello @rcocks, these endpoints didn't exist when we first implemented the wrapper. If you have some free time feel free to log a issue for the search your going to implement and then submit a PR that links it.

Looking at the docs it seems that if we implement `Search All` then the other ones will just use the same return types for desalinization. 

As always contributions are welcome and much appreciated.

Thanks

**Comment by kevbite** [comment]
All functionality is now implemented within version 3.0.0 (https://www.nuget.org/packages/CompaniesHouse/3.0.0), readme still needs updating for usage of new functionality but these are now outstanding issues, See #39, #42
