### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0,

### ISSUE THREAD

**Issue by St1ngR4y** [kevbite/CompaniesHouse.NET#45]
Hi I'm trying to use CompaniesHouse.Net in form code of an InfoPath form. 

When it gets to var result = await client.SearchAllAsync(request); it throws a Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, error, is I pudate to version 7 of Newtonsoft.Json its tries to reference version 6.

Please help.

**Comment by St1ngR4y** [comment]
![companieshouseerror](https://cloud.githubusercontent.com/assets/23097681/19764764/ad624c4c-9c3c-11e6-8a9e-e399ce96e236.JPG)

**Comment by St1ngR4y** [comment]
![companieshouseerror](https://cloud.githubusercontent.com/assets/23097681/19764800/da5eb00a-9c3c-11e6-99b8-989993dfb1c5.JPG)

**Comment by kevbite** [comment]
Did you upgrade to the latest version of `Json.Net` [nuget v9.0.1](https://www.nuget.org/packages/newtonsoft.json/9.0.1)?

If you require that version then you could use assembly redirects to redirect assembly version at app level (That's if InfoPath supports this) - https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx

Or If you don't require the latest version you could always just install v7.x.x which `CompaniesHouse.NET` uses:

```powershell

Install-Package Newtonsoft.Json -Version 7.0.1
```

Might be worth us updating to latest version of Json.Net anyway...

**Comment by St1ngR4y** [comment]
Hi thanks for the super quick reply.

When i install json.net v7 i get the same error but cannot reference v6? Also companieshouse.net installs v6 out of the box. I will look into the redirect but could it be a limitation of  infopath? Also i have to change .net versions from 4 to 4.5 in the code editor so could there be references set by that?

Thanks in advance im quite new to development so apologies if my wording is incorrect

**Comment by St1ngR4y** [comment]
![error2](https://cloud.githubusercontent.com/assets/23097681/19766367/44c20b10-9c45-11e6-9c15-412b8c9fdb8c.JPG)

**Comment by kevbite** [comment]
I've updated the packages try the latest version 😄

**Comment by St1ngR4y** [comment]
Hi thanks for the super quick reply. When i install json.net v7 i get the
same error but cannot reference v6? Also companieshouse.net installs v6 out
of the box. I will look into the redirect but could it be a limitation of
infopath? Also i have to change .net versions from 4 to 4.5 in the code
editor so could there be references set by that?

Thanks in advance im quite new to development so apologies if my wording is
incorrect.

Iain

On 27 Oct 2016 12:06, "Kevin Smith" <notifications@github.com> wrote:

Did you upgrade to the latest version of Json.Net nuget v9.0.1
<https://www.nuget.org/packages/newtonsoft.json/9.0.1>?

If you require that version then you could use assembly redirects to
redirect assembly version at app level (That's if InfoPath supports this) -
https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx

Or If you don't require the latest version you could always just install
v7.x.x which CompaniesHouse.NET uses:

Install-Package Newtonsoft.Json -Version 7.0.1

Might be worth us updating to latest version of Json.Net anyway...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kevbite/CompaniesHouse.NET/issues/45#issuecomment-256612259>,
or mute the thread

**Comment by kevbite** [comment]
@St1ngR4y did you get this sorted?

**Comment by kevbite** [comment]
Closing off issue.

**Comment by St1ngR4y** [comment]
Hi Kevin, no sorry had to drop the feature from he form. I tried everything
at the time to get it working but no luck.

On 27 Dec 2016 11:01, "Kevin Smith" <notifications@github.com> wrote:

@St1ngR4y <https://github.com/St1ngR4y> did you get this sorted?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kevbite/CompaniesHouse.NET/issues/45#issuecomment-269311045>,
or mute the thread

**Comment by kevbite** [comment]
OK no worries, did you try sticking anything on http://stackoverflow.com/ regarding using libraries and InfoPath form?
