### ISSUE TITLE
REQUEST - Addition of GET /company/{company_number}/insolvency API

### ISSUE THREAD

**Issue by Aenedor** [kevbite/CompaniesHouse.NET#48]
Thanks for all your guidance today Kevin :)

Please could you add the GET /company/{company_number}/insolvency API.

Best Regards

Peter

**Comment by kevbite** [comment]
@Aenedor do you have a company number for an insolvent company?

**Comment by Aenedor** [comment]
Hi Kev, here you go, 03044143

_On 2016-10-20, 03044143 went into Creditors Liquidation. Kenneth William Touhey , Insolvency & Recovery Ltd, at 2nd Floor, Chapelworth House, 1 Chatsworth Road, Worthing, West Sussex, BN11 1LY has been appointed Liquidator._

**Comment by Aenedor** [comment]
@kevbite Actually try this one 08749409, looks like the above was too recent

**Comment by kevbite** [comment]
Now implemented in version 3.1.0, see https://www.nuget.org/packages/CompaniesHouse/3.1.2
