### ISSUE TITLE
Default XML namespace error

### ISSUE THREAD

**Issue by Jibran18** [kevbite/CompaniesHouse.NET#59]
Hi,
I am new to companies house API and try to learn your code to make my own solution, but when I try to build solution on VS2013 it came up with error 

>  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format
I have tried to look into the internet to find out solution but not been able t.
Can you please advise what I am missing to run the companies house test api?

Thanks for your help in advance

Jibran

**Comment by kevbite** [comment]
Hello,
This project will not open with VS2013 as it uses cproj files with the new msbuild for dotnet core. You can however use VS2017 or dotnetcore CLI. this can be downloaded at https://www.microsoft.com/net/download/core
https://www.visualstudio.com/downloads/

If you're thinking about extending the project it might be worth pushing your changes back in to the OSS project for other people to benefit.

Kev

**Comment by kevbite** [comment]
For the time being I'm closing this issue, If you have any other problems just open up a new issue.

Thanks
