### ISSUE TITLE
VS2017 installation issue

### ISSUE THREAD

**Issue by Jibran18** [kevbite/CompaniesHouse.NET#60]
Hi,
I want to test the current companies house api application, but not been able to as it does only work with Visual Studio 2017. Can someone share with me the application compatible with other versions of visual studio. I am currently using visual studio 2015

**Comment by kevbite** [comment]
What do you mean by test? You should be able to install the package from nuget, search for `companieshouse`

**Comment by conficient** [comment]
Installed on VS2017 here, runs perfectly, no problems. It's probably your setup @Jibran18 that is at fault here?

**Comment by kevbite** [comment]
For the time being I'm closing this issue, If you have any other problems just open up a new issue.

Thanks
