### ISSUE TITLE
Unhandled CompanyType value `registered-society-non-jurisdictional`

### ISSUE THREAD

**Issue by conficient** [kevbite/CompaniesHouse.NET#62]
Thanks for the most excellent library!

I was washing our list through this and came across this error:
```
Message=Error converting value "registered-society-non-jurisdictional" to type 'CompaniesHouse.Response.CompanyType'. Path 'type', line 1, position 155.
```
Looks like the "Registered Society" type not is handled by the enum, e.g. https://beta.companieshouse.gov.uk/company/RS004345

I will be submitting a pull request to add this type to the code.

**Comment by kevbite** [comment]
Thanks for the PR, Companies House seem to have missed a few of these off their api spec before.

However all the changes are all merged in and we've pushed Companies House [3.2.1](https://www.nuget.org/packages/CompaniesHouse/3.2.1) to nuget.org
