### ISSUE TITLE
Charges and PersonsWithSignificantControl

### ISSUE THREAD

**Issue by digitalanalogue9** [kevbite/CompaniesHouse.NET#64]
Hi - are you accepting pull requests with new features?  

I've got a requirement at work to get the Charges and PersonsWithSignificantControl.  I'd like to get it into the codebase so other devs at work can just pull down the nuget package.

I wasn't sure if there was anything specific you wanted to see in the code.  I had one question over PersonsWithSignificantControl as it has 7 endpoints.  At the moment, I've implemented ICompaniesHousePersonsWithSignificantControlClient with all 7 endpoints in that interface (7 different uribuilders classes) but would you prefer to see them split into a I**Client per endpoint?

Thanks
Dan

**Comment by kevbite** [comment]
Hello,

I'm always up for new features/functionality being developed into this project, the only reason why It stopped where it has is that these are the set of APIs I required.

As for coding style, copying the current way is the best idea with regards to testing too.

At the moment `ICompaniesHouseClient` acts as a facade into the library which I'd like to keep it that way, makes it a lot easier to consume as a client.

So feel free to fan out the requests on to other objects but I'd like to see the main client have all the access methods (if that makes sense). 

Cheers,

Kev

**Comment by kevbite** [comment]
Hey @DanHibbert How's the work going? Do you need any help?

**Comment by wreid306** [comment]
Interested in both these items, would you have a rough timescale for these to be added in?

**Comment by kevbite** [comment]
@DanHibbert did you start any of this work? If not we're happy to take contributions to the project if you're happy implementing @wreid306?

**Comment by DanHibbert** [comment]
Really sorry for late reply !  
Hi @kevbite - yes I did but I got a bit waylaid on other projects and then a bit stuck on the unit test side of things.  The code is there and working but I need to get the tests working before sending it back.

**Comment by kevbite** [comment]
Hey @DanHibbert no worries about the time getting back to me, happy to wait or help along with what you've got if you want to submit a PR?

**Comment by sakisk** [comment]
Issues #119 and #120 created

**Comment by sakisk** [comment]
Closed via #119 and #120
