### ISSUE TITLE
Getting started with this library

### ISSUE THREAD

**Issue by AlwaysVbNet** [kevbite/CompaniesHouse.NET#68]
Hello, I am trying to use your library like below, but the object returned does not have any valid information. Any ideas what I'm doing wrong? Is the code updated to the latest API?
```
  Dim settings As New CompaniesHouseSettings("xxxxxxxxxxxxxxxxxxxxxxxxxx")
            Dim xx
            Using client As New CompaniesHouseClient(settings)
                xx = client.GetCompanyProfileAsync("12345678")
            End Using
```
then the "xx" object equals to:
```
AsyncState: nothing
CancellationPending: false
CreationOptions: none
Exception: nothing
Id = 107,
Status = WaitingForActivation {1}, 
Method = "{null}", 
Result = "{Not yet computed}
```

**Comment by kevbite** [comment]
Hello,
The `GetCompanyProfileAsync` returns a `Task<T>` so you'll need to `Await` on the task that is returned to get the response from the call.

You should be able to change your statement of:
```vb
xx = client.GetCompanyProfileAsync("12345678")
```
to
```
xx = Await client.GetCompanyProfileAsync("12345678")
```

However rthis has to run within an Async method. More details about how to do asynchronous programming in VB can be found here - https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/

Hope this is useful, however if you have any other questions feel free to ask.

Cheers,

Kev

**Comment by AlwaysVbNet** [comment]
Nice library. Good work
