### ISSUE TITLE
Company Type Enums Error

### ISSUE THREAD

**Issue by darrenc83** [kevbite/CompaniesHouse.NET#73]
Whilst using the API searching for the following company

brighouse computers

i got the below error:

Newtonsoft.Json.JsonSerializationException: Error converting value "charitable-incorporated-organisation" to type 'CompaniesHouse.Response.CompanyType'. Path 'company_type', line 1, position 2090. ---> System.ArgumentException: Requested value 'charitable-incorporated-organisation' was not found.

Upon further investigation i could see this enum type is missing from the API CompanyType Enum list.

Below is a list of all the latest Company Types i got direct from Companies House.

The company type. Possible values are:

private-unlimited
ltd
plc
old-public-company
private-limited-guarant-nsc-limited-exemption
limited-partnership
private-limited-guarant-nsc
converted-or-closed
private-unlimited-nsc
private-limited-shares-section-30-exemption
protected-cell-company
assurance-company
oversea-company
eeig
icvc-securities
icvc-warrant
icvc-umbrella
industrial-and-provident-society
northern-ireland
northern-ireland-other
llp
royal-charter
investment-company-with-variable-capital
unregistered-company
llp
other
european-public-limited-liability-company-se
scottish-partnership
charitable-incorporated-organisation
scottish-charitable-incorporated-organisation

**Comment by kevbite** [comment]
I've updated the companies types enum but there also seems to be companies coming back with `null` statuses that need changing too. I've logged this as a separate issue #74
