### ISSUE TITLE
Dissolved companies FilingCategory

### ISSUE THREAD

**Issue by AlwaysVbNet** [kevbite/CompaniesHouse.NET#77]
Kevin, 

when trying to get the filing history of company number "06454743" which appears to be "Dissolved"
an exception is thrown:

{"Error converting value ""restoration"" to type 'CompaniesHouse.Response.FilingCategory'. Path 'items[10].category', line 1, position 5612."}

Any ideas?

**Comment by kevbite** [comment]
Looks like they might have updated the `FilingCategory` values, we'll need to add `restoration` to the list of possible enum values in [FilingCategory.cs](https://github.com/kevbite/CompaniesHouse.NET/blob/master/src/CompaniesHouse/Response/FilingCategory.cs)

**Comment by kevbite** [comment]
Thanks for helping out with that, will be in next version after #78 has merged back to master and deployed.
