### ISSUE TITLE
Missing value 'notifications' in CompaniesHouse.Response.FilingSubcategory enum

### ISSUE THREAD

**Issue by vinhalo** [kevbite/CompaniesHouse.NET#79]
The following exception occurs when getting the Filing History for certain companies :

Error converting value \"notifications\" to type 'CompaniesHouse.Response.FilingSubcategory'.

**Comment by kevbite** [comment]
Hello, Do you have an id as an example so we can test this?

**Comment by vinhalo** [comment]
Hi there,

If you try getting the filing history (50 items per page) for company 10225670 you should encounter the error.

Thanks

**Comment by kevbite** [comment]
Thanks, I'll try to sort this out soonish... unless you fancy having a go and submitting a PR.

**Comment by vinhalo** [comment]
Yeah I can have a stab shouldn't be too difficult cheers.

**Comment by vinhalo** [comment]
PR submitted.

**Comment by kevbite** [comment]
Thanks, It's just building and will be released soon in version 4.0.5
