### ISSUE TITLE
GetCompanyFilingHistoryAsync() Officers not found

### ISSUE THREAD

**Issue by JulianGuppy** [kevbite/CompaniesHouse.NET#81]
When using the _companiesHouseClient.GetCompanyFilingHistoryAsync
with a company registration number of 0795823 (my old company)

i get the following crash: -

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib

Inner Exception 1:
JsonSerializationException: Error converting value "officers" to type 'CompaniesHouse.Response.FilingSubcategory'. Path 'items[23].subcategory', line 1, position 13014.

Inner Exception 2:
ArgumentException: Requested value 'officers' was not found.

What ever is coming from companies house for this business (new wave capital) is not liked. If you could investigate this I would be very happy!

**Comment by kevbite** [comment]
Hello, thanks for raising the issues.

The API will have been extended to pass back more values and we'll need to update our code to reflect these changes too.

These are small fixes, so I'll try to do them later on today.

**Comment by kevbite** [comment]
This should be fixed in the latest release [5.0.0](https://www.nuget.org/packages/CompaniesHouse/5.0.0) can you update the packages and test this is working and raise another issue if you're still having problems.

Thanks!
