### ISSUE TITLE
GetCompanyFilingHistoryAsync() Error converting Liquidation to type

### ISSUE THREAD

**Issue by JulianGuppy** [kevbite/CompaniesHouse.NET#82]
When using _companiesHouseClient.GetCompanyFilingHistoryAsync with a company registration number of 00059337 I get the following error:-

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
Inner Exception 1:
JsonSerializationException: Error converting value "liquidation" to type 'CompaniesHouse.Response.ResolutionCategory'. Path 'items[22].resolutions[0].category', line 1, position 11656.

Inner Exception 2:
ArgumentException: Requested value 'liquidation' was not found.

**Comment by kevbite** [comment]
This should be fixed in the latest release [5.0.0](https://www.nuget.org/packages/CompaniesHouse/5.0.0) can you update the packages and test this is working and raise another issue if you're still having problems.

Thanks!
