### ISSUE TITLE
Error converting value ""notifications"" 

### ISSUE THREAD

**Issue by AlwaysVbNet** [kevbite/CompaniesHouse.NET#89]
@kevbite , I'm getting an error when I'm trying to pull the Company Filing History for company reg 03914263
like `Await client.GetCompanyFilingHistoryAsync("03914263")`

`{"Error converting value ""notifications"" to type 'CompaniesHouse.Response.FilingSubcategory'. Path 'items[4].subcategory', line 1, position 2536."}`

Any ideas?

**Comment by kevbite** [comment]
I've just added that company number to the integration tests and seems to be working fine.

https://ci.appveyor.com/project/kevbite/companieshouse-net/build/0.0.0-issue89185

I think you might be running an older version of the NuGet package, try updating to the latest version

https://www.nuget.org/packages/CompaniesHouse/6.1.0
