### ISSUE TITLE
'Company Type' Convert Error

### ISSUE THREAD

**Issue by wreid306** [kevbite/CompaniesHouse.NET#91]
Hi Kev - error when searching company, seems we need a new company type added:

{"Error converting value \"scottish-charitable-incorporated-organisation\" to type 'CompaniesHouse.Response.CompanyType'. Path 'company_type', line 1, position 3319."}

Would it be possible, in the event of company type not parsing, having maybe an enum 'Other' and then the value as an addition string field?

**Comment by kevbite** [comment]
Hey @wreid306, I'll add this as it's a quick fix... but I'll also add an issue to be able to fall back to an `Other` value.

**Comment by kevbite** [comment]
@wreid306 just checked and it looks like this value is part of the latest build. Can you update to the latest NuGet package and try it again?

**Comment by wreid306** [comment]
Hi Kev, updated to v6.1.1 and now getting this for the same query

![image](https://user-images.githubusercontent.com/10054139/46792082-602a9200-cd3a-11e8-9359-ffff0ecd5f90.png)

**Comment by wreid306** [comment]
Thats the query if it helps 

![image](https://user-images.githubusercontent.com/10054139/46792458-4fc6e700-cd3b-11e8-8cc3-143e1a05ba81.png)

**Comment by wreid306** [comment]
ahh shoot! Ill take another look here, I must be doing something silly! 

Cheers for your help!

**Comment by wreid306** [comment]
Yep, I was being an idiot, although i updated to latest version in nuget, it somehow kept a reference to an older version... just sorted it and its working now!

**Comment by kevbite** [comment]
Glad you've got it sorted! Going to close this issue but feel free to open another one if you experience any other problems.
