### ISSUE TITLE
Getting filing history #bug

### ISSUE THREAD

**Issue by AlwaysVbNet** [kevbite/CompaniesHouse.NET#95]
@kevbite I am trying to get the filing history for company reg "06484911" but I get the following error:

`{"Error converting value ""auditors"" to type 'CompaniesHouse.Response.ResolutionCategory'. Path 'items[12].resolutions[0].category', line 1, position 6271."} `

I am using the latest version of the project.

I noticed this error a few times for different categories. Is there a way to fallback somehow instead of breaking the call every time?

**Comment by kevbite** [comment]
Hello, the problem is there is no definitive list in their [API docs](https://developer.companieshouse.gov.uk/api/docs/company/company_number/filing-history/filingHistoryItem-resource.html), we could have a fallback value for the enums but then we'd never know if something went wrong or not.

**Comment by kevbite** [comment]
Fixed in version [6.1.3](https://www.nuget.org/packages/CompaniesHouse/6.1.3)
